config/routes.rb
Rails.application.routes.draw do

  devise_for :admins

  get 'star_wars' => 'star_wars#index'
  get 'star_wars/roll' => redirect('star_wars')
  get 'star_wars/roll(/a:a)(/p:p)(/d:d)(/c:c)(/b:b)(/s:s)(/f:f)' => 'star_wars#roll'
  post 'star_wars/roll' => 'star_wars#roll', :defaults => { :format => 'js' }
  get 'star_wars/clear' => 'star_wars#clear_log'
  get 'star_wars/log' => 'star_wars#get_log'

  get 'genesys' => 'genesys#index'
  get 'genesys/roll' => redirect('genesys')
  get 'api/v1/genesys/roll(/a:a)(/p:p)(/d:d)(/c:c)(/b:b)(/s:s)(/f:f)' => 'genesys#api_roll', :defaults => { :format => 'json' }
  post 'genesys/roll' => 'genesys#roll', :defaults => { :format => 'js' }
  get 'genesys/clear' => 'genesys#clear_log'
  get 'genesys/log' => 'genesys#get_log'

  get 'xwing' => 'xwing#index'
  get 'xwing/roll' => redirect('xwing')
  get 'xwing/roll(/a:a)(/p:p)(/d:d)(/c:c)(/b:b)(/s:s)(/f:f)' => 'xwing#roll'
  post 'xwing/roll' => 'xwing#roll', :defaults => { :format => 'js' }
  get 'xwing/clear' => 'xwing#clear_log'
  get 'xwing/log' => 'xwing#get_log'

  get 'polyhedron' => 'polyhedron#index'
  get 'polyhedron/roll' => redirect('polyhedron')
  get 'api/v1/polyhedron/roll(/a:a)(/p:p)(/d:d)(/c:c)(/b:b)(/s:s)(/f:f)' => 'polyhedron#api_roll', :defaults => { :format => 'json' }
  post 'polyhedron/roll' => 'polyhedron#roll', :defaults => { :format => 'js' }
  get 'polyhedron/clear' => 'polyhedron#clear_log'
  get 'polyhedron/log' => 'polyhedron#get_log'

  get 'about' => 'pages#about'

  get 'rolls/trim' => 'rolls#trim_log'
  get 'rolls/truncate' => 'rolls#truncate_log'
  get 'rolls/geoloc' => 'rolls#geoloc'
  get 'rolls(/:uuid)' => 'rolls#index'
  resources :rolls

  root 'genesys#index'

end

app/controllers/polyhedron_controller.rb
class PolyhedronController < ApplicationController
  include ApplicationHelper
  include ActionView::Helpers::TextHelper

  before_action :set_page
  #before_action :initialize_dice

  def index
    embedded = params['embed'].present?

    @dice_results = []

    @dice_rolled = {
      d4: params['d4'].present? ? params['d4'] : 0,
      d4mod: params['d4mod'].present? ? params['d4mod'] : 0,
      d6: params['d6'].present? ? params['d6'] : 0,
      d6mod: params['d6mod'].present? ? params['d6mod'] : 0,
      d8: params['d8'].present? ? params['d8'] : 0,
      d8mod: params['d8mod'].present? ? params['d8mod'] : 0,
      d10: params['d10'].present? ? params['d10'] : 0,
      d10mod: params['d10mod'].present? ? params['d10mod'] : 0,
      d12: params['d12'].present? ? params['d12'] : 0,
      d12mod: params['d12mod'].present? ? params['d12mod'] : 0,
      d20: params['d20'].present? ? params['d20'] : 0,
      d20mod: params['d20mod'].present? ? params['d20mod'] : 0,
      d100: params['d100'].present? ? params['d100'] : 0,
      d100mod: params['d100mod'].present? ? params['d100mod'] : 0,
      keep: params['keep'].present? ? params['keep'] : 'true',
      log: params['log'].present? ? params['log'] : 'true',
      tag: params['tag'].present? ? params['tag'] : '',
      embedded: embedded
    }

    respond_to do |format|
      format.html
    end
  end

  def roll
    if params[:commit].present?
      @roll_params_dice = {
        d4: params[:d4].to_i || 0,
        d6: params[:d6].to_i || 0,
        d8: params[:d8].to_i || 0,
        d10: params[:d10].to_i || 0,
        d12: params[:d12].to_i || 0,
        d20: params[:d20].to_i || 0,
        d100: params[:d100].to_i || 0,
      }
      @roll_params_mods = {
        d4mod: params[:d4mod].to_i || 0,
        d6mod: params[:d6mod].to_i || 0,
        d8mod: params[:d8mod].to_i || 0,
        d10mod: params[:d10mod].to_i || 0,
        d12mod: params[:d12mod].to_i || 0,
        d20mod: params[:d20mod].to_i || 0,
        d100mod: params[:d100mod].to_i || 0,
      }

      @roll_log = []

      roll_check = @roll_params_dice.values.inject { |a, b| a.to_i  + b.to_i }
      if roll_check > 0
        @dice_result = get_dice_results(@roll_params_dice, @roll_params_mods)
        @results = @dice_result
        @result_text = []
        @roll_tag = params[:tag] || ''

        @log_dice_text = ''
        @log_result_text = ''
        if (params[:persist])
          @log_date = Time.now.to_i
          log_dice_text = []
          log_result_text = []
          @results.each do |result|
            next if result[1][:rolls].blank?
            log_dice_text << "#{result[1][:rolls].count}#{result[0].upcase}#{sprintf("%+d", result[1][:modifier]) if result[1][:modifier] != 0}"
            log_result_text << result[1][:total]
          end
          @log_dice_text = log_dice_text.to_sentence(words_connector: "<br>", last_word_connector: "<br>", two_words_connector: '<br>') || ''
          @log_result_text = log_result_text.to_sentence(words_connector: "<br>", last_word_connector: "<br>", two_words_connector: '<br>') || ''
        end
      end
    end
  end

  private

  def get_dice_results(roll_params_dice, roll_params_mods)
    dice_results = {
      d4: { rolls: [], modifier: roll_params_mods[:d4mod], total: 0, icon: 'd4' },
      d6: { rolls: [], modifier: roll_params_mods[:d6mod], total: 0, icon: 'd6' },
      d8: { rolls: [], modifier: roll_params_mods[:d8mod], total: 0, icon: 'd8' },
      d10: { rolls: [], modifier: roll_params_mods[:d10mod], total: 0, icon: 'd1' },
      d12: { rolls: [], modifier: roll_params_mods[:d12mod], total: 0, icon: 'd12' },
      d20: { rolls: [], modifier: roll_params_mods[:d20mod], total: 0, icon: 'd20' },
      d100: { rolls: [], modifier: roll_params_mods[:d100mod], total: 0, icon: 'd100' },
    }

    roll_params_dice[:d4].to_i.times do
      dice_results[:d4][:rolls] << rand(1..4)
    end
    dice_results[:d4][:total] = dice_results[:d4][:rolls].sum + dice_results[:d4][:modifier]

    roll_params_dice[:d6].to_i.times do
      dice_results[:d6][:rolls] << rand(1..6)
    end
    dice_results[:d6][:total] = dice_results[:d6][:rolls].sum + dice_results[:d6][:modifier]

    roll_params_dice[:d8].to_i.times do
      dice_results[:d8][:rolls] << rand(1..8)
    end
    dice_results[:d8][:total] = dice_results[:d8][:rolls].sum + dice_results[:d8][:modifier]

    roll_params_dice[:d10].to_i.times do
      dice_results[:d10][:rolls] << rand(1..10)
    end
    dice_results[:d10][:total] = dice_results[:d10][:rolls].sum + dice_results[:d10][:modifier]

    roll_params_dice[:d12].to_i.times do
      dice_results[:d12][:rolls] << rand(1..12)
    end
    dice_results[:d12][:total] = dice_results[:d12][:rolls].sum + dice_results[:d12][:modifier]

    roll_params_dice[:d20].to_i.times do
      dice_results[:d20][:rolls] << rand(1..20)
    end
    dice_results[:d20][:total] = dice_results[:d20][:rolls].sum + dice_results[:d20][:modifier]

    roll_params_dice[:d100].to_i.times do
      dice_results[:d100][:rolls] << rand(1..100)
    end
    dice_results[:d100][:total] = dice_results[:d100][:rolls].sum + dice_results[:d100][:modifier]

    dice_results
  end

  def set_page
    @page = 'polyhedron_rpg'
    @parent_page = 'rollers'
    @system = 'polyhedron'
  end

end

app/views/polyhedron/_poly_dice_amount.html.haml
.input-group.mb-1{ data: { dice: dice } }
  .input-group-prepend.decrease
    %span.input-group-text= "-"
  = number_field_tag(dice.to_sym, @dice_rolled[dice.to_sym], { id: dice, min: 0, class: 'dice form-control', style: '' })
  .input-group-append.increase
    %span.input-group-text= "+"

app/views/polyhedron/_poly_dice_modifier.html.haml
.input-group.mb-1{ data: { dice: "#{dice}mod" } }
  .input-group-prepend.decrease
    %span.input-group-text= "-"
  = number_field_tag("#{dice}mod".to_sym, @dice_rolled["#{dice}mod".to_sym], { id: "#{dice}mod", class: 'dice form-control', style: '' })
  .input-group-append.increase
    %span.input-group-text= "+"

app/views/polyhedron/clear_log.js.erb
$('#roll-log').html("<%= escape_javascript(render(partial: 'shared/roll_log', locals: { log: @roll_log })).html_safe %>");

app/views/polyhedron/get_log.html.haml
= render partial: 'shared/roll_log', locals: { log: @roll_log }

app/views/polyhedron/index.html.haml
- content_for :title do
  Polyhedral Dice

.row.hidden-modal
  .col-sm-12
    %h1
      Polyhedral Dice
.row
  .col-sm-12
    #dice-result{'aria-hidden':"true"}
    .row
      .col-sm-12.col-md-8
        #dice-rolling{'aria-hidden':"true"}
          .card.mb-3.bg-light
            .card-body
              = image_tag('dice/polyhedron/rolling.gif', size: '100')
        = form_tag(polyhedron_roll_path, id: 'polyhedron-roll', remote: true) do
          .row
            .col-12
              .diceTable
                .diceTableRow
                  .diceTableHead
                    Dice
                  .diceTableHead.text-center
                    Amount
                  .diceTableHead.text-center
                    Modifier
                .diceTableRow
                  .diceTableCell.label D4
                  .diceTableCell
                    = render partial: 'poly_dice_amount', locals: {dice: 'd4'}
                  .diceTableCell
                    = render partial: 'poly_dice_modifier', locals: {dice: 'd4'}
                .diceTableRow
                  .diceTableCell.label  D6
                  .diceTableCell
                    = render partial: 'poly_dice_amount', locals: {dice: 'd6'}
                  .diceTableCell
                    = render partial: 'poly_dice_modifier', locals: {dice: 'd6'}
                .diceTableRow
                  .diceTableCell.label  D8
                  .diceTableCell
                    = render partial: 'poly_dice_amount', locals: {dice: 'd8'}
                  .diceTableCell
                    = render partial: 'poly_dice_modifier', locals: {dice: 'd8'}
                .diceTableRow
                  .diceTableCell.label  D10
                  .diceTableCell
                    = render partial: 'poly_dice_amount', locals: {dice: 'd10'}
                  .diceTableCell
                    = render partial: 'poly_dice_modifier', locals: {dice: 'd10'}
                .diceTableRow
                  .diceTableCell.label  D12
                  .diceTableCell
                    = render partial: 'poly_dice_amount', locals: {dice: 'd12'}
                  .diceTableCell
                    = render partial: 'poly_dice_modifier', locals: {dice: 'd12'}
                .diceTableRow
                  .diceTableCell.label  D20
                  .diceTableCell
                    = render partial: 'poly_dice_amount', locals: {dice: 'd20'}
                  .diceTableCell
                    = render partial: 'poly_dice_modifier', locals: {dice: 'd20'}
                .diceTableRow
                  .diceTableCell.label D100
                  .diceTableCell
                    = render partial: 'poly_dice_amount', locals: {dice: 'd100'}
                  .diceTableCell
                    = render partial: 'poly_dice_modifier', locals: {dice: 'd100'}
          .row
            .col-sm-12.hidden-modal
              .row
                .col-sm-6
                  .form-check
                    - if @dice_rolled[:keep] == 'true'
                      = check_box_tag(:keep_dice, 1, {:checked => "checked"}, class: 'form-check-input')
                    - else
                      = check_box_tag(:keep_dice, 1, false, class: 'form-check-input')
                    %label.form-check-label{:for => "keep_dice"}
                      Remember dice
                  .form-check
                    - if @dice_rolled[:log] == 'true'
                      = check_box_tag(:persist, 1, {:checked => "checked"}, class: 'form-check-input')
                    - else
                      = check_box_tag(:persist, 1, false, class: 'form-check-input')
                    %label.form-check-label{:for => "persist"}
                      Save roll to log
                .col-sm-6
                  .input-group.mb-3
                    = text_field_tag(:tag, @dice_rolled[:tag], { id: 'tag', class: 'tag form-control', placeholder: 'Tag or short description'})
          .row
            .col-sm-12.mt-3
              .form-actions
                = hidden_field_tag(:user_uuid, @user_uuid)
                = submit_tag 'Roll Dice', class: 'btn btn-primary'
                = link_to "Clear Dice", '/polyhedron/clear', class: 'btn btn-outline-info clear hidden-modal'

.row.hidden-modal
  .col-sm-12{'aria-hidden':"true"}
    #roll-log
      = render partial: 'shared/roll_log'

.row.hidden-modal
  .col-sm-12{'aria-hidden':"true"}
    Select the dice to roll and click the button.
    /Share roll results on gaming forums using bbCode or RuBB.

app/views/polyhedron/roll.js.erb
$('#dice-result').html("<%= escape_javascript(render(partial: 'shared/dice_results', locals: { results: @dice_result, result_text: @raw_result_text, system: @system })).html_safe %>");
$('#computed-result').html("<%= escape_javascript(render(partial: 'shared/computed_results', locals: { results: @results, result_text: @result_text, system: @system })).html_safe %>");
$('#dice-rolling').hide()
$('#dice-result').show()
$('#computed-result').show()

if ('<%= @log_date %>'.length > 0) {
 log = JSON.parse(localStorage.getItem('roll_log_polyhedron')) || []

 if (log.length >= DiceRoller.logLimit()) {
  log.pop();
 }

 log.push({
   "time": '<%= @log_date %>',
   "diceText": '<%= escape_javascript(@log_dice_text.html_safe) %>',
   "resultText": '<%= escape_javascript(@log_result_text.html_safe) %>',
   "tag": '<%= escape_javascript(@roll_tag) %>',
 })

 try {
   localStorage.setItem('roll_log_polyhedron', JSON.stringify(log));
 } catch (e) {
   if (e == QUOTA_EXCEEDED_ERR) {
     alert('Quota exceeded!');
   }
 }

  // Populate log table.
  var last_log = log[log.length - 1];

  t = $('#roll-log-table').DataTable();
  t.row.add([
    //log.length,
    DiceRoller.formatLogDate(last_log.time),
    last_log.diceText,
    last_log.resultText,
    last_log.tag,
    "<div class='btn-group' role='group' data-dice-rolled='" + last_log.diceText + "' data-log-id='" + (log.length - 1) + "'><button class='btn btn-sm btn-success reroll-from-log'>Reroll</button><button class='btn btn-sm btn-danger delete-from-log'>Delete</button></div>"
  ]).select().draw(false);
}

// Hide stuff in in modal.
var loc = window.location.href;
if(loc.includes('embed=modal')) {
  $('#polyhedron-roll').hide();
}

function sleep(milliseconds) {
  var start = new Date().getTime();
  for (var i = 0; i < 1e7; i++) {
    if ((new Date().getTime() - start) > milliseconds){
      break;
    }
  }
}