config/routes.rb
Rails.application.routes.draw do

  devise_for :admins

  get 'star_wars' => 'star_wars#index'
  get 'star_wars/roll' => redirect('star_wars')
  get 'star_wars/roll(/a:a)(/p:p)(/d:d)(/c:c)(/b:b)(/s:s)(/f:f)' => 'star_wars#roll'
  post 'star_wars/roll' => 'star_wars#roll', :defaults => { :format => 'js' }
  get 'star_wars/clear' => 'star_wars#clear_log'
  get 'star_wars/log' => 'star_wars#get_log'

  get 'genesys' => 'genesys#index'
  get 'genesys/roll' => redirect('genesys')
  get 'api/v1/genesys/roll(/a:a)(/p:p)(/d:d)(/c:c)(/b:b)(/s:s)(/f:f)' => 'genesys#api_roll', :defaults => { :format => 'json' }
  post 'genesys/roll' => 'genesys#roll', :defaults => { :format => 'js' }
  get 'genesys/clear' => 'genesys#clear_log'
  get 'genesys/log' => 'genesys#get_log'

  get 'xwing' => 'xwing#index'
  get 'xwing/roll' => redirect('xwing')
  get 'xwing/roll(/a:a)(/p:p)(/d:d)(/c:c)(/b:b)(/s:s)(/f:f)' => 'xwing#roll'
  post 'xwing/roll' => 'xwing#roll', :defaults => { :format => 'js' }
  get 'xwing/clear' => 'xwing#clear_log'
  get 'xwing/log' => 'xwing#get_log'

  get 'polyhedron' => 'polyhedron#index'
  get 'polyhedron/roll' => redirect('polyhedron')
  get 'api/v1/polyhedron/roll(/a:a)(/p:p)(/d:d)(/c:c)(/b:b)(/s:s)(/f:f)' => 'polyhedron#api_roll', :defaults => { :format => 'json' }
  post 'polyhedron/roll' => 'polyhedron#roll', :defaults => { :format => 'js' }
  get 'polyhedron/clear' => 'polyhedron#clear_log'
  get 'polyhedron/log' => 'polyhedron#get_log'

  get 'about' => 'pages#about'

  get 'rolls/trim' => 'rolls#trim_log'
  get 'rolls/truncate' => 'rolls#truncate_log'
  get 'rolls/geoloc' => 'rolls#geoloc'
  get 'rolls(/:uuid)' => 'rolls#index'
  resources :rolls

  root 'genesys#index'

end

app/controllers/genesys_controller.rb
class GenesysController < ApplicationController
  include ApplicationHelper
  include ActionView::Helpers::TextHelper

  before_action :set_page
  before_action :initialize_dice

  def index
    embedded = params['embed'].present?

    @dice_results = []
    @successes = 0
    @advantages = 0
    @triumphs = 0
    @failures = 0
    @threats = 0
    @despairs = 0

    @dice_rolled = {
      a: params['a'].present? ? params['a'] : 0,
      d: params['d'].present? ? params['d'] : 0,
      p: params['p'].present? ? params['p'] : 0,
      c: params['c'].present? ? params['c'] : 0,
      b: params['b'].present? ? params['b'] : 0,
      s: params['s'].present? ? params['s'] : 0,
      keep: params['keep'].present? ? params['keep'] : 'true',
      log: params['log'].present? ? params['log'] : 'true',
      tag: params['tag'].present? ? params['tag'] : '',
      embedded: embedded
    }

    respond_to do |format|
      format.html
    end
  end

  def roll
    if params[:commit].present?
      @roll_params = {
        a: params[:a].to_i || 0,
        d: params[:d].to_i || 0,
        p: params[:p].to_i || 0,
        c: params[:c].to_i || 0,
        b: params[:b].to_i || 0,
        s: params[:s].to_i || 0,
        percent: params[:percent].to_i || 0,
      }

      @roll_log = []

      roll_check = @roll_params.values.inject { |a, b| a.to_i  + b.to_i }
      if roll_check > 0
        @roll_params = @roll_params.delete_if { |_key, value| value.to_i < 1 }

        @dice_result = get_dice_results(@roll_params)
        @results = get_results(@dice_result)
        @raw_result_text = get_raw_result_text(@dice_result)
        @result_text = get_result_text(@dice_result)
        @roll_tag = params[:tag] || ''

        if (params[:persist])
          @log_date = Time.now.to_i
          @log_dice_text = get_dice_text(@roll_params.symbolize_keys).join(', ') unless @roll_params.nil?
          if get_result_text(@dice_result).blank?
            @log_result_text = "*Wash*"
          else
            @log_result_text = get_result_text(@dice_result).join(', ')
          end
        end
      end
    end
  end

  def api_roll
    @roll_params = {
      a: params[:a].to_i || 0,
      d: params[:d].to_i || 0,
      p: params[:p].to_i || 0,
      c: params[:c].to_i || 0,
      b: params[:b].to_i || 0,
      s: params[:s].to_i || 0,
      percent: params[:percent].to_i || 0,
    }

    roll_json = {}

    roll_check = @roll_params.values.inject { |a, b| a.to_i  + b.to_i }
    if roll_check > 0
      @roll_params = @roll_params.delete_if { |_key, value| value.to_i < 1 }

      @dice_result = get_dice_results(@roll_params)
      @results = get_results(@dice_result)
      @raw_result_text = get_raw_result_text(@dice_result)
      @result_text = get_result_text(@dice_result)

      roll_json = {
        roll_params: @roll_params,
        dice_result: @dice_result,
        results: @results,
        raw_result_text: @raw_result_text,
        result_text: @result_text,
      }
    end

    respond_to do |format|
      format.html { redirect_to @adversary, notice: 'Dice was rolled' }
      format.json { render json: roll_json, status: :ok }
    end
  end

  private

  def get_dice_results(roll_params)
    dice_results = []

    roll_params.each do |roll|
      roll[1].to_i.times do
        case roll[0]
        when :a
          dice = @ability_dice
        when :d
          dice = @difficulty_dice
        when :p
          dice = @proficiency_dice
        when :c
          dice = @challenge_dice
        when :b
          dice = @boost_dice
        when :s
          dice = @setback_dice
        when :percent
          dice = 'd100'
        end

        icon = []
        if dice == 'd100'
          dice_name = 'd100'
          side = rand(1..100)
          faces = []#[*1..100]
          icon = ['d100']
        else
          dice_name = dice.name
          side = rand(1..dice.num_sides)
          faces = dice.send("side#{side}")

          faces.each do |face|
            face[1].times do
              icon << face[0].to_s
            end
          end
        end

        dice_results << {
          dice: dice_name,
          side: side,
          faces: faces,
          icon: icon.any? ? icon.join('-') : 'blank'
        }
      end
    end

    dice_results
  end

  def get_raw_result_text(dice_results)
    successes = 0
    advantages = 0
    triumphs = 0
    failures = 0
    threats = 0
    despairs = 0

    dice_results.each do |result|
      result.symbolize_keys!
      result[:faces].each do |face|
        case face[0].to_sym
        when :success
          successes += face[1]
        when :advantage
          advantages += face[1]
        when :triumph
          triumphs += face[1]
        when :failure
          failures += face[1]
        when :threat
          threats += face[1]
        when :despair
          despairs += face[1]
        end
      end
    end

    result_text = []
    result_text << pluralize(successes, 'success') if successes > 0
    result_text << pluralize(advantages, 'advantage') if advantages > 0
    result_text << pluralize(triumphs, 'triumph') if triumphs > 0
    result_text << pluralize(failures, 'failure') if failures > 0
    result_text << pluralize(threats, 'threat') if threats > 0
    result_text << pluralize(despairs, 'despair') if despairs > 0
    result_text
  end

  def get_results(dice_results)
    results = {
      successes: 0,
      advantages: 0,
      triumphs: 0,
      failures: 0,
      threats: 0,
      despairs: 0,
    }

    dice_results.each do |result|
      result.symbolize_keys!
      result[:faces].each do |face|
        case face[0].to_sym
        when :success
          results[:successes] += face[1]
        when :advantage
          results[:advantages] += face[1]
        when :triumph
          results[:triumphs] += face[1]
        when :failure
          results[:failures] += face[1]
        when :threat
          results[:threats] += face[1]
        when :despair
          results[:despairs] += face[1]
        end
      end
    end

    # Add triumphs to sucesses.
    results[:successes] += results[:triumphs]

    # Add despairs to failures.
    results[:failures] += results[:despairs]

    # Subtract failures from successes.
    results[:failures].times do
      break if results[:successes] == 0
      results[:successes] -= 1
      results[:failures] -= 1
    end

    # Subtract threats from advantages.
    results[:threats].times do
      break if results[:advantages] == 0
      results[:advantages] -= 1
      results[:threats] -= 1
    end

    results
  end

  def initialize_dice
    @ability_dice = AbilityDice.new
    @proficiency_dice = ProficiencyDice.new
    @difficulty_dice = DifficultyDice.new
    @challenge_dice = ChallengeDice.new
    @boost_dice = BoostDice.new
    @setback_dice = SetbackDice.new
  end

  def set_page
    @page = 'genesys_rpg'
    @parent_page = 'rollers'
    @system = 'genesys'
  end

end

app/views/genesys/clear_log.js.erb
$('#roll-log').html("<%= escape_javascript(render(partial: 'shared/roll_log', locals: { log: @roll_log })).html_safe %>");

app/views/genesys/get_log.html.haml
= render partial: 'shared/roll_log', locals: { log: @roll_log }

app/views/genesys/index.html.haml
- content_for :title do
  Genesys (FFG)

.row.hidden-modal
  .col-sm-12
    %h1
      Genesys RPG
      %small FFG narrative system
.row
  .col-sm-12
    #dice-result{'aria-hidden':"true"}
      - if @latest_roll
        = render partial: 'shared/dice_results', locals: { results: @latest_roll['dice_result'], result_text: @latest_roll['raw_result_text'], system: @latest_roll['system'] }
    #computed-result
      - if @latest_roll
        = render partial: 'shared/computed_results', locals: { results: @latest_roll['results'], result_text: @latest_roll['result_text'], system: @latest_roll['system'] }
    /.row
    /  .col-sm-12.columns
    /    = @roll_path
    .row
      .col-sm-12.col-md-8
        #dice-rolling{'aria-hidden':"true"}
          .card.mb-3.bg-light
            .card-body
              = image_tag('dice/genesys/rolling.gif', size: '100')
        = form_tag(genesys_roll_path, id: 'genesys-roll', remote: true) do
          .row
            .col-sm-6.col-md
              .input-group.mb-3{ data: { dice: 'ability' } }
                .input-group-prepend.decrease
                  %span.input-group-text.rotateimg180= image_tag('genesys/buttons/ability_dec.svg', size: '45')
                = number_field_tag(:a, @dice_rolled[:a], { id: 'ability', min: 0, class: 'dice form-control', style: '' })
                .input-group-append.increase
                  %span.input-group-text= image_tag('genesys/buttons/ability_inc.svg', size: '45')
            .col-sm-6
              .input-group.mb-3{ data: { dice: 'proficiency' } }
                .input-group-prepend.decrease
                  %span.input-group-text.rotateimg180= image_tag('genesys/buttons/proficiency_dec.svg', size: '45')
                = number_field_tag(:p, @dice_rolled[:p], { id: 'proficiency', min: 0, class: 'dice form-control' })
                .input-group-append.increase
                  %span.input-group-text= image_tag('genesys/buttons/proficiency_inc.svg', size: '45')
            .col-sm-6
              .input-group.mb-3{ data: { dice: 'difficulty' } }
                .input-group-prepend.decrease
                  %span.input-group-text.rotateimg180= image_tag('genesys/buttons/difficulty_dec.svg', size: '45')
                = number_field_tag(:d, @dice_rolled[:d], { id: 'difficulty', min: 0, class: 'dice form-control' })
                .input-group-append.increase
                  %span.input-group-text= image_tag('genesys/buttons/difficulty_inc.svg', size: '45')
            .col-sm-6
              .input-group.mb-3{ data: { dice: 'challenge' } }
                .input-group-prepend.decrease
                  %span.input-group-text.rotateimg180= image_tag('genesys/buttons/challenge_dec.svg', size: '45')
                = number_field_tag(:c, @dice_rolled[:c], { id: 'challenge', min: 0, class: 'dice form-control' })
                .input-group-append.increase
                  %span.input-group-text= image_tag('genesys/buttons/challenge_inc.svg', size: '45')
            .col-sm-6
              .input-group.mb-3{ data: { dice: 'boost' } }
                .input-group-prepend.decrease
                  %span.input-group-text.rotateimg180= image_tag('genesys/buttons/boost_dec.svg', size: '45')
                = number_field_tag(:b, @dice_rolled[:b], { id: 'boost', min: 0, class: 'dice form-control' })
                .input-group-append.increase
                  %span.input-group-text= image_tag('genesys/buttons/boost_inc.svg', size: '45')
            .col-sm-6
              .input-group.mb-3{ data: { dice: 'setback' } }
                .input-group-prepend.decrease
                  %span.input-group-text.rotateimg180= image_tag('genesys/buttons/setback_dec.svg', size: '45')
                = number_field_tag(:s, @dice_rolled[:s], { id: 'setback', min: 0, class: 'dice form-control' })
                .input-group-append.increase
                  %span.input-group-text= image_tag('genesys/buttons/setback_inc.svg', size: '45')
          .col-sm-12.hidden-modal
            .row
              .col-sm-6
                .form-check
                  - if @dice_rolled[:keep] == 'true'
                    = check_box_tag(:keep_dice, 1, {:checked => "checked"}, class: 'form-check-input')
                  - else
                    = check_box_tag(:keep_dice, 1, false, class: 'form-check-input')
                  %label.form-check-label{:for => "keep_dice"}
                    Remember dice
                .form-check
                  - if @dice_rolled[:log] == 'true'
                    = check_box_tag(:persist, 1, {:checked => "checked"}, class: 'form-check-input')
                  - else
                    = check_box_tag(:persist, 1, false, class: 'form-check-input')
                  %label.form-check-label{:for => "persist"}
                    Save roll to log
              .col-sm-6
                .input-group.mb-3
                  = text_field_tag(:tag, @dice_rolled[:tag], { id: 'tag', class: 'tag form-control', placeholder: 'Tag or short description'})
          .col-sm-12.mt-3
            .form-actions
              = hidden_field_tag(:user_uuid, @user_uuid)
              = submit_tag 'Roll Dice', class: 'btn btn-primary'
              = link_to "Clear Dice", '/genesys/clear', class: 'btn btn-outline-info clear hidden-modal'

      /- if @dice_results.any?
      /  .col-sm-12.col-md-4.panel.hide-for-small-only{'aria-hidden':"true"}
      /    .col-sm-12
      /      %button.tiny#rubbcode_clip_button.my_clip_button{"data-clipboard-target" => "rubbcode", "data-clipboard-text" => "", :title => "Click me to copy to clipboard."}
      /        %b Copy result RuBB Code To Clipboard
      /      %small#rubbcode<
      /        = @rubbcode.join
      /    .col-sm-12
      /      %button.tiny#bbcode_clip_button.my_clip_button{"data-clipboard-target" => "bbcode", "data-clipboard-text" => "", :title => "Click me to copy to clipboard."}
      /        %b Copy result bbCode To Clipboard
      /      %small#bbcode<
      /        = @bbcode.join

.row.hidden-modal
  .col-sm-12{'aria-hidden':"true"}
    #roll-log
      = render partial: 'shared/roll_log'

.row.hidden-modal
  .col-sm-12{'aria-hidden':"true"}
    This is a dice roller for the Genesys RPG line from Fantasy Flight Games.
    Select the dice to roll and click the button.
    /Share roll results on gaming forums using bbCode or RuBB.

app/views/genesys/roll.js.erb
$('#dice-result').html("<%= escape_javascript(render(partial: 'shared/dice_results', locals: { results: @dice_result, result_text: @raw_result_text, system: @system })).html_safe %>");
$('#computed-result').html("<%= escape_javascript(render(partial: 'shared/computed_results', locals: { results: @results, result_text: @result_text, system: @system })).html_safe %>");
$('#dice-rolling').hide()
$('#dice-result').show()
$('#computed-result').show()

if ('<%= @log_date %>'.length > 0) {
 log = JSON.parse(localStorage.getItem('roll_log_genesys')) || []

 if (log.length >= DiceRoller.logLimit()) {
  log.pop();
 }

 log.push({
   "time": '<%= @log_date %>',
   "diceText": '<%= escape_javascript(@log_dice_text) %>',
   "resultText": '<%= escape_javascript(@log_result_text) %>',
   "tag": '<%= escape_javascript(@roll_tag) %>',
 })

 try {
   localStorage.setItem('roll_log_genesys', JSON.stringify(log));
 } catch (e) {
   if (e == QUOTA_EXCEEDED_ERR) {
     alert('Quota exceeded!');
   }
 }

  // Populate log table.
  var last_log = log[log.length - 1];

  t = $('#roll-log-table').DataTable();
  t.row.add([
    //log.length,
    DiceRoller.formatLogDate(last_log.time),
    last_log.diceText,
    last_log.resultText,
    last_log.tag,
    "<div class='btn-group' role='group' data-dice-rolled='" + last_log.diceText + "' data-log-id='" + (log.length - 1) + "'><button class='btn btn-sm btn-success reroll-from-log'>Reroll</button><button class='btn btn-sm btn-danger delete-from-log'>Delete</button></div>"
  ]).select().draw(false);
}

// Hide stuff in in modal.
var loc = window.location.href;
if(loc.includes('embed=modal')) {
  $('#genesys-roll').hide();
}

function sleep(milliseconds) {
  var start = new Date().getTime();
  for (var i = 0; i < 1e7; i++) {
    if ((new Date().getTime() - start) > milliseconds){
      break;
    }
  }
}