config/routes.rb
Rails.application.routes.draw do

  devise_for :admins

  get 'star_wars' => 'star_wars#index'
  get 'star_wars/roll' => redirect('star_wars')
  get 'star_wars/roll(/a:a)(/p:p)(/d:d)(/c:c)(/b:b)(/s:s)(/f:f)' => 'star_wars#roll'
  post 'star_wars/roll' => 'star_wars#roll', :defaults => { :format => 'js' }
  get 'star_wars/clear' => 'star_wars#clear_log'
  get 'star_wars/log' => 'star_wars#get_log'

  get 'genesys' => 'genesys#index'
  get 'genesys/roll' => redirect('genesys')
  get 'api/v1/genesys/roll(/a:a)(/p:p)(/d:d)(/c:c)(/b:b)(/s:s)(/f:f)' => 'genesys#api_roll', :defaults => { :format => 'json' }
  post 'genesys/roll' => 'genesys#roll', :defaults => { :format => 'js' }
  get 'genesys/clear' => 'genesys#clear_log'
  get 'genesys/log' => 'genesys#get_log'

  get 'xwing' => 'xwing#index'
  get 'xwing/roll' => redirect('xwing')
  get 'xwing/roll(/a:a)(/p:p)(/d:d)(/c:c)(/b:b)(/s:s)(/f:f)' => 'xwing#roll'
  post 'xwing/roll' => 'xwing#roll', :defaults => { :format => 'js' }
  get 'xwing/clear' => 'xwing#clear_log'
  get 'xwing/log' => 'xwing#get_log'

  get 'polyhedron' => 'polyhedron#index'
  get 'polyhedron/roll' => redirect('polyhedron')
  get 'api/v1/polyhedron/roll(/a:a)(/p:p)(/d:d)(/c:c)(/b:b)(/s:s)(/f:f)' => 'polyhedron#api_roll', :defaults => { :format => 'json' }
  post 'polyhedron/roll' => 'polyhedron#roll', :defaults => { :format => 'js' }
  get 'polyhedron/clear' => 'polyhedron#clear_log'
  get 'polyhedron/log' => 'polyhedron#get_log'

  get 'about' => 'pages#about'

  get 'rolls/trim' => 'rolls#trim_log'
  get 'rolls/truncate' => 'rolls#truncate_log'
  get 'rolls/geoloc' => 'rolls#geoloc'
  get 'rolls(/:uuid)' => 'rolls#index'
  resources :rolls

  root 'genesys#index'

end

app/models/roll.rb
class Roll < ActiveRecord::Base
  #paginates_per 10

  serialize :roll_params
  serialize :dice_result
  serialize :raw_result_text
  serialize :results
  serialize :result_text
  serialize :geoloc

  def origin_of_roll
    require 'net/http'

    origin = []
    ip_lookup = JSON.parse(Net::HTTP.get_response(URI.parse('http://ipinfo.io/' + ip )).body)

    unless ip_lookup['city'].blank?
      origin << ip_lookup['city']
    end
    unless ip_lookup['region'].blank?
      origin << ip_lookup['region']
    end
    unless ip_lookup['country'].blank?
      origin << ip_lookup['country']
    end

    origin
  end

end

app/controllers/rolls_controller.rb
class RollsController < ApplicationController
  before_action :authenticate_admin!, except: [:index, :truncate_log]
  before_action :set_roll, only: [:show, :edit, :update, :destroy]

  # GET /rolls
  # GET /rolls.json
  def index
    if params[:uuid]
      @rolls = Roll.where(uuid: params[:uuid]).order(created_at: :desc).page params[:page]
    else
      @rolls = Roll.order(created_at: :desc).page params[:page]
    end
  end

  # POST /rolls
  # POST /rolls.json
  def create
    @roll = Roll.new(roll_params)

    respond_to do |format|
      if @roll.save
        format.html { redirect_to @roll, notice: 'Roll was successfully created.' }
        format.json { render :show, status: :created, location: @roll }
      else
        format.html { render :new }
        format.json { render json: @roll.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /rolls/1
  # PATCH/PUT /rolls/1.json
  def update
    respond_to do |format|
      if @roll.update(roll_params)
        format.html { redirect_to @roll, notice: 'Roll was successfully updated.' }
        format.json { render :show, status: :ok, location: @roll }
      else
        format.html { render :edit }
        format.json { render json: @roll.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /rolls/1
  # DELETE /rolls/1.json
  def destroy
    @roll.destroy
    respond_to do |format|
      format.html { redirect_to rolls_url, notice: 'Roll was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def trim_log
    @trim_date = 14.days.ago
    @count = 0

    roll_log = Roll.where("created_at < ?", @trim_date)

    roll_log.each do |log|
      @count += 1
      log.destroy
    end

    flash[:notice] = "Trimmed #{@count} dice logs from before: #{Time.at(@trim_date).to_datetime.in_time_zone}"
    redirect_to rolls_url
  end

  def truncate_log
    ActiveRecord::Base.connection.execute("TRUNCATE rolls")
    flash[:notice] = "Cleared all dice roll logs."
    redirect_to rolls_url
  end

  def geoloc
    rolls = Roll.all

    rolls.each do |roll|
      roll.geoloc = roll.origin_of_roll
      roll.save
    end
    redirect_to rolls_url
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_roll
      @roll = Roll.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def roll_params
      params.require(:roll).permit(:ability, :difficulty, :proficiency, :challenge, :boost, :setback, :dice_result, :results, :raw_result_text, :result_text, :roll_params, :ip, :uuid, :system)
    end
end

app/views/rolls/_form.html.haml
= form_for @roll do |f|
  - if @roll.errors.any?
    #error_explanation
      %h2= "#{pluralize(@roll.errors.count, "error")} prohibited this roll from being saved:"
      %ul
        - @roll.errors.full_messages.each do |msg|
          %li= msg

  .field
    = f.label :ability
    = f.number_field :ability
  .field
    = f.label :difficulty
    = f.number_field :difficulty
  .field
    = f.label :proficiency
    = f.number_field :proficiency
  .field
    = f.label :challenge
    = f.number_field :challenge
  .field
    = f.label :boost
    = f.number_field :boost
  .field
    = f.label :setback
    = f.number_field :setback
  .field
    = f.label :dice_result
    = f.text_field :dice_result
  .field
    = f.label :results
    = f.text_field :results
  .field
    = f.label :raw_result_text
    = f.text_field :raw_result_text
  .field
    = f.label :result_text
    = f.text_field :result_text
  .field
    = f.label :roll_params
    = f.text_field :roll_params
  .field
    = f.label :ip
    = f.text_field :ip
  .field
    = f.label :uuid
    = f.text_field :uuid
  .field
    = f.label :system
    = f.text_field :system
  .actions
    = f.submit 'Save'

app/views/rolls/edit.html.haml
%h1 Editing roll

= render 'form'

= link_to 'Show', @roll
\|
= link_to 'Back', rolls_path

app/views/rolls/index.html.haml
- content_for :title do
  Star Wars (FFG)

.row
  .col-sm-12
    %h1 Dice rolls
.row
  .col-sm-12
    - if admin_signed_in?
      = link_to 'Trim log', rolls_trim_path, class: 'button tiny'
      = link_to 'Truncate log', rolls_truncate_path, class: 'button tiny'
      = link_to 'Update geolocs', rolls_geoloc_path, class: 'button tiny'
    %table.rolls.table
      %thead
        %tr
          %th Date
          %th Dice
          /%th Dice result
          %th Results
          /%th Raw result text
          /%th Result text
          /%th Roll params
          - if admin_signed_in?
            %th Origin
          %th Uuid
          %th System
          - if admin_signed_in?
            %th

      %tbody
        - @rolls.each do |roll|
          %tr
            %td= roll.created_at.strftime("%F")
            - if roll.system == 'genesys' || roll.system == 'star_wars'
              %td{width:240}
                .dice.ability= roll.ability
                .dice.difficulty= roll.difficulty
                .dice.proficiency= roll.proficiency
                .dice.challenge= roll.challenge
                .dice.boost= roll.boost
                .dice.setback= roll.setback
            - if roll.system == 'xwing'
              %td{width:60}
                .dice.attack= roll.attack
                .dice.defense= roll.defense
            /%td= roll.dice_result.class
            %td
              %span.has-tip{"aria-haspopup" => "true", "data-tooltip" => "", :title => roll.result_text.to_sentence}
                - if roll.results[:successes]
                  - roll.results[:successes].times do
                    = image_tag("symbols/#{roll.system}/success.png", size: '20', title: 'Success')
                - if roll.results[:advantages]
                  - roll.results[:advantages].times do
                    = image_tag("symbols/#{roll.system}/advantage.png", size: '20')
                - if roll.results[:triumphs]
                  - roll.results[:triumphs].times do
                    = image_tag("symbols/#{roll.system}/triumph.png", size: '20')
                - if roll.results[:failures]
                  - roll.results[:failures].times do
                    = image_tag("symbols/#{roll.system}/failure.png", size: '20')
                - if roll.results[:threats]
                  - roll.results[:threats].times do
                    = image_tag("symbols/#{roll.system}/threat.png", size: '20')
                - if roll.results[:despairs]
                  - roll.results[:despairs].times do
                    = image_tag("symbols/#{roll.system}/despair.png", size: '20')
                - if roll.results[:blacks]
                  - roll.results[:blacks].times do
                    = image_tag("symbols/#{roll.system}/force_black.png", size: '20')
                - if roll.results[:whites]
                  - roll.results[:whites].times do
                    = image_tag("symbols/#{roll.system}/force_white.png", size: '20')
                - if roll.results[:hits]
                  - roll.results[:hits].times do
                    = image_tag("symbols/#{roll.system}/hit.png", size: '20')
                - if roll.results[:crits]
                  - roll.results[:crits].times do
                    = image_tag("symbols/#{roll.system}/crit.png", size: '20')
                - if roll.results[:evades]
                  - roll.results[:evades].times do
                    = image_tag("symbols/#{roll.system}/evade.png", size: '20')
                - if roll.results[:focuses]
                  - roll.results[:focuses].times do
                    = image_tag("symbols/#{roll.system}/focus.png", size: '20')
            - if admin_signed_in?
              %td
                - if roll.geoloc.nil? || roll.geoloc.empty?
                  = roll.ip
                - else
                  = roll.geoloc.join(', ')
            %td= roll.uuid
            %td= roll.system.humanize.titleize unless roll.system.nil?
            - if admin_signed_in?
              %td= link_to 'Destroy', roll, :method => :delete, :data => { :confirm => 'Are you sure?' }

    %br
    = paginate @rolls

app/views/rolls/new.html.haml
%h1 New roll

= render 'form'

= link_to 'Back', rolls_path

app/views/rolls/show.html.haml
%p#notice= notice

%p
  %b Ability:
  = @roll.ability
%p
  %b Difficulty:
  = @roll.difficulty
%p
  %b Proficiency:
  = @roll.proficiency
%p
  %b Challenge:
  = @roll.challenge
%p
  %b Boost:
  = @roll.boost
%p
  %b Setback:
  = @roll.setback
%p
  %b Dice result:
  = @roll.dice_result
%p
  %b Results:
  = @roll.results
%p
  %b Raw result text:
  = @roll.raw_result_text
%p
  %b Result text:
  = @roll.result_text
%p
  %b Roll params:
  = @roll.roll_params
%p
  %b Ip:
  = @roll.ip
%p
  %b Uuid:
  = @roll.uuid
%p
  %b System:
  = @roll.system

= link_to 'Edit', edit_roll_path(@roll)
\|
= link_to 'Back', rolls_path