config/routes.rb
Rails.application.routes.draw do

  devise_for :admins

  get 'star_wars' => 'star_wars#index'
  get 'star_wars/roll' => redirect('star_wars')
  get 'star_wars/roll(/a:a)(/p:p)(/d:d)(/c:c)(/b:b)(/s:s)(/f:f)' => 'star_wars#roll'
  post 'star_wars/roll' => 'star_wars#roll', :defaults => { :format => 'js' }
  get 'star_wars/clear' => 'star_wars#clear_log'
  get 'star_wars/log' => 'star_wars#get_log'

  get 'genesys' => 'genesys#index'
  get 'genesys/roll' => redirect('genesys')
  get 'api/v1/genesys/roll(/a:a)(/p:p)(/d:d)(/c:c)(/b:b)(/s:s)(/f:f)' => 'genesys#api_roll', :defaults => { :format => 'json' }
  post 'genesys/roll' => 'genesys#roll', :defaults => { :format => 'js' }
  get 'genesys/clear' => 'genesys#clear_log'
  get 'genesys/log' => 'genesys#get_log'

  get 'xwing' => 'xwing#index'
  get 'xwing/roll' => redirect('xwing')
  get 'xwing/roll(/a:a)(/p:p)(/d:d)(/c:c)(/b:b)(/s:s)(/f:f)' => 'xwing#roll'
  post 'xwing/roll' => 'xwing#roll', :defaults => { :format => 'js' }
  get 'xwing/clear' => 'xwing#clear_log'
  get 'xwing/log' => 'xwing#get_log'

  get 'polyhedron' => 'polyhedron#index'
  get 'polyhedron/roll' => redirect('polyhedron')
  get 'api/v1/polyhedron/roll(/a:a)(/p:p)(/d:d)(/c:c)(/b:b)(/s:s)(/f:f)' => 'polyhedron#api_roll', :defaults => { :format => 'json' }
  post 'polyhedron/roll' => 'polyhedron#roll', :defaults => { :format => 'js' }
  get 'polyhedron/clear' => 'polyhedron#clear_log'
  get 'polyhedron/log' => 'polyhedron#get_log'

  get 'about' => 'pages#about'

  get 'rolls/trim' => 'rolls#trim_log'
  get 'rolls/truncate' => 'rolls#truncate_log'
  get 'rolls/geoloc' => 'rolls#geoloc'
  get 'rolls(/:uuid)' => 'rolls#index'
  resources :rolls

  root 'genesys#index'

end

app/views/layouts/_flash.html.haml
- if flash[:error]
  .row
    .col-sm-12
      .alert-box.warning.radius{"data-alert" => ""}
        = h flash[:error].html_safe
- if flash[:notice]
  .row
    .col-sm-12
      .alert-box.info.radius{"data-alert" => ""}
        = h flash[:notice].html_safe
- if flash[:success]
  .row
    .col-sm-12
      .alert-box.success.radius{"data-alert" => ""}
        = h flash[:success].html_safe
- if flash[:alert]
  .row
    .col-sm-12
      .alert-box.warning.radius{"data-alert" => ""}
        = h flash[:alert].html_safe

app/views/layouts/_gtm_noscript.html.erb
<!-- Google Tag Manager (noscript) -->
<noscript><iframe src="https://www.googletagmanager.com/ns.html?id=GTM-MV9QMTW"
height="0" width="0" style="display:none;visibility:hidden"></iframe></noscript>
<!-- End Google Tag Manager (noscript) -->

app/views/layouts/_header.html.haml
/ Fixed navbar
%nav.navbar.navbar-expand-md.navbar-dark.fixed-top.bg-dark.hidden-modal
  -#%button#sidebarCollapse.btn.btn-sm.btn-info.mr-4{:type => "button"}
  -#  %i{'data-feather': "menu", 'stroke-width': "1"}
  -#  %span Menu
  %a.navbar-brand{:href => "/"} RPG Dice Roller
  %button.navbar-toggler{"aria-controls" => "navbarCollapse", "aria-expanded" => "false", "aria-label" => "Toggle navigation", "data-target" => "#navbarCollapse", "data-toggle" => "collapse", :type => "button"}
    %span.navbar-toggler-icon
  #navbarCollapse.collapse.navbar-collapse
    %ul.navbar-nav.mr-auto
      %li.nav-item{class: current_class?(genesys_path)}
        #{link_to "Genesys RPG", genesys_path, class: 'nav-link'}
      %li.nav-item{class: current_class?(star_wars_path)}
        #{link_to "Star Wars RPG", star_wars_path, class: 'nav-link'}
      %li.nav-item{class: current_class?(xwing_roll_path)}
        #{link_to "Star Wars X-wing minis", xwing_roll_path, class: 'nav-link'}
      %li.nav-item{class: current_class?(polyhedron_roll_path)}
        #{link_to "Polyhedral Dice", polyhedron_roll_path, class: 'nav-link'}

    %ul.navbar-nav.ml-auto
      %li.nav-item.pr-3{class: ("active" if current_page('about'))}
        #{link_to 'About', about_path, class: 'nav-link'}
      -#%li.nav-item= render 'layouts/patreon'
      -#%li.nav-item
      -#  .nav-link or
      %li.nav-item= render 'layouts/kofi_donate'
      -#%li.nav-item{ class: current_class?(main_app.root_path) }
      -#  = link_to 'Home', main_app.root_path, class: 'nav-link'
      -#%li.nav-item{ class: current_class?(user_characters_path(current_user)) }
      -#  = link_to 'Characters', user_characters_path(current_user), class: 'btn btn-info'
      -#%li.nav-item{ class: current_class?(main_app.me_path) }
      -#  = link_to 'Profile', main_app.me_path, class: 'nav-link'
      -#%li.nav-item
      -#  = link_to 'Sign out', main_app.logout_path, class: 'nav-link'
    -#%form.form-inline.mt-2.mt-md-0
    -#  %input.form-control.mr-sm-2{"aria-label" => "Search", :placeholder => "Search", :type => "text"}/
    -#  %button.btn.btn-outline-success.my-2.my-sm-0{:type => "submit"} Search

app/views/layouts/_kofi_donate.html.erb
<a href='https://ko-fi.com/C0C6C0XN' target='_blank'><img height='30' style='border:0px;height:36px; padding: 0;' src='https://az743702.vo.msecnd.net/cdn/kofi4.png?v=0' border='0' alt='Buy Me a Coffee at ko-fi.com' /></a>

app/views/layouts/_main_menu.html.haml
.top-bar
  .top-bar-left
    %ul.dropdown.menu{"data-dropdown-menu" => ""}
      %li.menu-text RPG Dice Roller
      %li{class: current_class?(genesys_path)}
        #{link_to "Genesys RPG", genesys_path}
      %li{class: current_class?(star_wars_path)}
        #{link_to "Star Wars RPG", star_wars_path}
      %li{class: current_class?(xwing_roll_path)}
        #{link_to "Star Wars X-wing minis", xwing_roll_path}
      %li{class: current_class?(polyhedron_roll_path)}
        #{link_to "Regular Dice", polyhedron_roll_path}
  .top-bar-right
    %ul.menu
      %li{class: ("active" if current_page('about'))}
        #{link_to 'About', about_path}
      %li= render 'layouts/kofi_donate'

-#%nav.top-bar{"data-topbar" => ""}
-#  %ul.title-area
-#    %li.name
-#      %h1= link_to 'RPG Dice Roller', root_path
-#    %li.toggle-topbar.menu-icon
-#      %a{href: "#"}
-#        %span Menu
-#  %section.top-bar-section
-#    / Right Nav Section
-#    %ul.right
-#      %li{class: ("active" if current_page('about'))}
-#        #{link_to 'About', about_path}
-#      /%li= render 'layouts/paypal_donate'
-#      %li= render 'layouts/kofi_donate'
-#
-#    / Left Nav Section
-#    %ul.left
-#      /%li.has-dropdown{class: ("active" if parent_page('rollers'))}
-#      /  %a{href: "#"} Dice Rollers
-#      /  %ul.dropdown
-#      %li{class: current_class?(genesys_path)}
-#        #{link_to "Genesys RPG", genesys_path}
-#      %li{class: current_class?(star_wars_path)}
-#        #{link_to "Star Wars RPG", star_wars_path}
-#      %li{class: current_class?(xwing_roll_path)}
-#        #{link_to "Star Wars X-wing minis", xwing_roll_path}
-#

app/views/layouts/_patreon.html.erb
<a href="https://www.patreon.com/bePatron?u=283886" data-patreon-widget-type="become-patron-button">Become a Patron!</a><script async src="https://c6.patreon.com/becomePatronButton.bundle.js"></script>

app/views/layouts/_paypal_donate.html.erb
<form action="https://www.paypal.com/cgi-bin/webscr" method="post" target="_top">
<input type="hidden" name="cmd" value="_s-xclick">
<input type="hidden" name="hosted_button_id" value="AT6C7A6CB2BJN">
<input type="image" src="https://www.paypalobjects.com/en_US/i/btn/btn_donate_SM.gif" border="0" name="submit" alt="PayPal - The safer, easier way to pay online!">
<img alt="" border="0" src="https://www.paypalobjects.com/en_US/i/scr/pixel.gif" width="1" height="1">
</form>

app/views/layouts/application.html.haml
-#!!!
-#%html{lang: "en"}
-#  %head
-#    %meta{charset: "utf-8"}/
-#    %meta{content: "width=device-width, initial-scale=1.0", name: "viewport"}/
-#    %title
-#      = content_for?(:title) ? yield(:title) : (@title ? @title : "")
-#      | RPG Dice Roller
-#    = stylesheet_link_tag    "application"
-#    =# javascript_include_tag "vendor/modernizr", 'data-turbolinks-track': 'reload'
-#    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'
-#    = csrf_meta_tags
-#  %body{ class: "#{controller_name} #{action_name}"}
-#    .row
-#      .small-12
-#        = render partial: 'layouts/main_menu'
-#    #flash_messages= render partial: 'layouts/flash'
-#    = yield
-#  =# render 'cookies_eu/consent_banner'
-#  =# javascript_include_tag "application"
-#
-#:javascript
-#  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
-#  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
-#  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
-#  })(window,document,'script','//www.google-analytics.com/analytics.js','ga');
-#
-#  ga('create', 'UA-63980058-1', 'auto');
-#  ga('send', 'pageview');
-#
!!!
%html.no-js{:lang => "en"}
  %head
    / Google Tag Manager
    :javascript
      (function(w,d,s,l,i){w[l]=w[l]||[];w[l].push({'gtm.start':
      new Date().getTime(),event:'gtm.js'});var f=d.getElementsByTagName(s)[0],
      j=d.createElement(s),dl=l!='dataLayer'?'&l='+l:'';j.async=true;j.src=
      'https://www.googletagmanager.com/gtm.js?id='+i+dl;f.parentNode.insertBefore(j,f);
      })(window,document,'script','dataLayer','GTM-MV9QMTW');
    / End Google Tag Manager

    :javascript
        document.documentElement.className += (window.self == window.top ? " top" : " framed");
    / Required meta tags
    %meta{:charset => "utf-8"}/
    %meta{:content => "ie=edge", "http-equiv" => "x-ua-compatible"}/
    %meta{:content => "", :name => "description"}/
    %meta{:content => "width=device-width, initial-scale=1", :name => "viewport"}/
    / Place favicon.ico in the root directory
    %title
      = content_for?(:title) ? yield(:title) : (@title ? @title : "")
      | RPG Dice Roller
    = csrf_meta_tags
    = stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload'
    = stylesheet_link_tag "application", media: 'print'

    %script{:crossorigin => "anonymous", :integrity => "sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN", :src => "https://code.jquery.com/jquery-3.2.1.slim.min.js"}
    %script{:crossorigin => "anonymous", :integrity => "sha384-b/U6ypiBEHpOf/4+1nzFpr53nxSS+GLCkfwBdFNTxtclqqenISfwAzpKaMNFNmj4", :src => "https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.11.0/umd/popper.min.js"}

    =# javascript_include_tag 'tinymce'
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'

    %link{:href => "https://cdn.datatables.net/1.10.19/css/jquery.dataTables.css", :rel => "stylesheet", :type => "text/css"}/
    -#%link{:href => "https://cdnjs.cloudflare.com/ajax/libs/select2/4.0.6-rc.0/css/select2.min.css", :rel => "stylesheet"}/
    =# stylesheet_link_tag "select2-bootstrap4-theme/dist/select2-bootstrap4.min", media: 'all'
    -#%script{:src => "https://cdnjs.cloudflare.com/ajax/libs/select2/4.0.6-rc.0/js/select2.min.js"}

  %body{:class => "#{controller_name} #{action_name}", data: {system: @system}}
    = render partial: 'layouts/gtm_noscript'
    = render partial: 'layouts/header'
    %main.container{:role => "main"}
      = render partial: 'layouts/flash'
      = yield

    / Optional JavaScript
    / jQuery first, then Popper.js, then Bootstrap JS
    /%script{:charset => "utf8", :src => "https://cdn.datatables.net/1.10.19/js/jquery.dataTables.js", :type => "text/javascript"}
    = javascript_include_tag 'bootstrap'
    =# javascript_include_tag 'jquery.knob'
    =#:javascript
    =#  feather.replace()